id: Unisolate Endpoint - Generic
name: Unisolate Endpoint - Generic
description: "This playbook unisolates endpoints according to the endpoint ID or host
  name provided in the playbook.\nIt currently supports the following integrations:\n
  - Carbon Black Response\n- Cortex XDR\n- Crowdstrike Falcon\n- FireEye HX \n- Cybereason\n
  - Microsoft Defender For Endpoint."
trigger:
steps:
- id: 2a0f3a1c-748a-4019-87d4-87a90fbe5bfb
  type: start
  description: ''
  action:
  connector:
  inputs: {}
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: c878cab8-cdaa-407d-8b39-6cd26b7361b0
  type: subplaybook
  description: This playbook unisolates sensors according to the sensor ID that is
    provided in the playbook input.
  action:
  connector:
  inputs:
    Endpoint_ID:
      complex:
        root: inputs.Endpoint_ID
        transformers:
        - operator: uniq
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: 712259a3-c95a-423f-8639-431fb8d514c7
  type: subplaybook
  description: This playbook unisolates endpoints according to the endpoint ID that
    is provided in the playbook input.
  action:
  connector:
  inputs:
    Endpoint_ID:
      complex:
        root: inputs.Endpoint_ID
        transformers:
        - operator: uniq
    Hostname:
      complex:
        root: inputs.Hostname
        transformers:
        - operator: uniq
    IP:
      complex:
        root: inputs.IP
        transformers:
        - operator: uniq
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: a42fe062-acbe-448c-82c4-f7cdfdf15b82
  type: title
  description: ''
  action:
  connector:
  inputs: {}
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: c62a1b36-38d0-4069-854c-8c5e6bdae135
  type: subplaybook
  description: This playbook unisolates devices according to the device ID that is
    provided in the playbook input.
  action:
  connector:
  inputs:
    Endpoint_id:
      complex:
        root: inputs.Endpoint_ID
        transformers:
        - operator: uniq
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: 80b6c790-1aef-4d56-8d48-8b0446ac6e31
  type: subplaybook
  description: This playbook unisolates endpoints according to the hostname/endpoint
    ID that is provided by the playbook input.
  action:
  connector:
  inputs:
    Endpoint_id:
      simple: ${inputs.Endpoint_ID}
    Hostname:
      simple: ${inputs.Hostname}
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: b4313ff8-dec2-4f6e-8fc9-31f06e13fbc9
  type: subplaybook
  description: This playbook unisolates a machine based on the hostname provided.
  action:
  connector:
  inputs:
    Hostname:
      complex:
        root: inputs.Hostname
        transformers:
        - operator: uniq
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: 1ecf253b-6e06-4b5e-8a05-00161e93be16
  type: subplaybook
  description: This playbook accepts an endpoint ID, IP, or host name and unisolates
    it using the Microsoft Defender For Endpoint integration.
  action:
  connector:
  inputs:
    Device_id:
      complex:
        root: inputs.Endpoint_ID
        transformers:
        - operator: uniq
    Hostname:
      complex:
        root: inputs.Hostname
        transformers:
        - operator: uniq
    Device_IP:
      complex:
        root: inputs.IP
        transformers:
        - operator: uniq
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
inputs:
outputs:
metadata:
  vendor_mappings: {}
