id: 7c5946d2-be83-4991-8b67-fdc568166260
name: Action - Domain - Block (Indicator)
description: Blocks the indicators of type 'Domain' on the firewall and marks the
  indicator as "Blocked" based on its Block status.
trigger:
steps:
- id: 8bfb13ed-331b-4a25-abc7-2e18ec697f43
  type: WorkflowStep
  description:
  action: Overwrite
  connector:
  inputs:
    resource:
      content: <p>{{vars.loggedInUserName}}&nbsp;initiated block of {{vars.indicatorValue}}
        with the following reasons:&nbsp;{{vars.actionReason}}</p>
      __replace: ''
      indicators: '{{vars.indicatorIRI}}'
    _showJson: false
    operation: Overwrite
    collection: /api/3/comments
    fieldOperation:
      recordTags: Overwrite
    step_variables: []
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: 048004a8-8e37-4974-a915-148cf22b7a29
  type: Title
  description:
  action:
  connector:
  inputs:
    actionReason: "{{\nvars.input.params.inputActionReasons\nif vars.input.params.inputActionReasons\n
      else vars.input.params.actionReason\n}}"
    indicatorIRI: "{{\nvars.input.params.inputIndicatorRecordIRI \nif vars.input.params.inputIndicatorRecordIRI
      \nelse  \nvars.input.records[0]['@id'] \n}}"
    indicatorValue: "{{\nvars.input.params.inputIndicatorValue\nif vars.input.params.inputIndicatorValue\n
      else \nvars.input.records[0].value\n}}"
    loggedInUserName: '{{vars.loggedInUser.firstname}} {{vars.loggedInUser.lastname}}'
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: 6f514bab-dddb-40b8-a0f0-929ab7d5a997
  type: Manual Task
  description:
  action:
  connector:
  inputs:
    type: DecisionBased
    input:
      schema:
        title: Block {{vars.indicatorValue}}
        description: "<p>Configure your firewall to block:&nbsp;{{vars.indicatorValue}}
          and Click \"Block Completed\" to confirm the status.</p>\n<p>*Consider changing
          this step to automation using a connector. That would accelerate your response
          time and allow you to focus on advanced threats</p>"
        inputVariables: []
    record: '{{ vars.input.records[0]["@id"] }}'
    resources: indicators
    owner_detail:
      isAssigned: false
    step_variables: []
    response_mapping:
      options:
      - option: Block Completed
        primary: true
        step_iri: /api/3/workflow_steps/f69b2682-2ffe-4e4e-9333-41e77e86ef7e
      - option: Unable to Block
        step_iri: /api/3/workflow_steps/30d908ba-e5d5-48b6-bc31-59f96bbf0568
      duplicateOption: false
  outputs:
  conditions:
  - if_: ''
    then: f69b2682-2ffe-4e4e-9333-41e77e86ef7e
    else_:
  - if_: ''
    then: 30d908ba-e5d5-48b6-bc31-59f96bbf0568
    else_:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: f69b2682-2ffe-4e4e-9333-41e77e86ef7e
  type: WorkflowStep
  description:
  action: Overwrite
  connector:
  inputs:
    message:
      tags: []
      type: /api/3/picklists/ff599189-3eeb-4c86-acb0-a7915e85ac3b
      tenant: ''
      content: '<p><span class="icon icon-successful text-success"  style="font-size:
        15px; color: green; font-weight: bold;"></span>{{vars.indicatorValue}} has
        been <strong>Blocked</strong> as confirmed by&nbsp;{{vars.loggedInUserName}}</p>'
      records: ''
    resource:
      indicatorStatus:
        id: 367
        '@id': /api/3/picklists/fa29fe48-f01e-476f-bb33-c910f5795b57
        icon:
        '@type': Picklist
        color:
        display: Blocked
        listName: /api/3/picklist_names/e6639d57-94a9-432f-a46f-b2b530402077
        itemValue: Blocked
        orderIndex: 0
    _showJson: false
    operation: Overwrite
    collection: '{{vars.indicatorIRI}}'
    collectionType: /api/3/indicators
    fieldOperation:
      recordTags: Overwrite
    step_variables: []
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: 30d908ba-e5d5-48b6-bc31-59f96bbf0568
  type: WorkflowStep
  description:
  action: Overwrite
  connector:
  inputs:
    message:
      tags: []
      type: /api/3/picklists/ff599189-3eeb-4c86-acb0-a7915e85ac3b
      content: <p>{{vars.indicatorValue}} was <strong>not blocked&nbsp;</strong>as
        confirmed by&nbsp;{{vars.loggedInUserName}}</p>
      records: ''
    resource:
      indicatorStatus:
        id: 369
        '@id': /api/3/picklists/2f5cff61-fbff-4bb3-96be-302b78a9fb47
        icon:
        '@type': Picklist
        color:
        display: TBD
        listName: /api/3/picklist_names/e6639d57-94a9-432f-a46f-b2b530402077
        itemValue: TBD
        orderIndex: 2
    _showJson: false
    operation: Overwrite
    collection: '{{vars.indicatorIRI}}'
    collectionType: /api/3/indicators
    fieldOperation:
      recordTags: Overwrite
    step_variables: []
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
- id: a458f14a-b98a-403a-ba6a-3ad8a606c9ac
  type: Start
  description:
  action:
  connector:
  inputs:
    route: 628e7f8d-ac98-431f-a401-56009b2ee022
    title: Block Domain
    resources:
    - indicators
    inputVariables:
    - name: actionReason
      type: string
      label: Reason
      tooltip: Specify Reason for the action
      dataType: text
      formType: text
      required: false
      _expanded: true
      _nameTouched: true
      defaultValue: Found malicious during investigation
      useRecordFieldDefault: false
    step_variables:
      input:
        params:
          actionReason: '{{vars.request.data["actionReason"]}}'
          inputActionReasons: '{{ vars.inputActionReasons }}'
          inputIndicatorValue: '{{ vars.inputIndicatorValue }}'
          inputIndicatorRecordIRI: '{{ vars.inputIndicatorRecordIRI }}'
        records: '{{vars.input.records}}'
      loggedInUser: '{{vars.currentUser | fromIRI }}'
    _promptexpanded: true
    displayConditions:
      indicators:
        sort: []
        limit: 30
        logic: AND
        filters:
        - type: object
          field: indicatorStatus
          value: /api/3/picklists/fa29fe48-f01e-476f-bb33-c910f5795b57
          _value:
            '@id': /api/3/picklists/fa29fe48-f01e-476f-bb33-c910f5795b57
            itemValue: Blocked
          operator: neq
        - type: object
          field: typeofindicator
          value: /api/3/picklists/5a5a7d42-be27-4903-858a-19909ebfa1eb
          _value:
            '@id': /api/3/picklists/5a5a7d42-be27-4903-858a-19909ebfa1eb
            display: Domain
            itemValue: Domain
          operator: eq
    executeButtonText: Block
    noRecordExecution: false
    singleRecordExecution: true
  outputs:
  conditions:
  subplaybooks:
  parallel:
  instructions:
  timeout:
  escalation:
  runtime:
  script_content:
  task_definition:
inputs:
outputs:
metadata:
  vendor_mappings: {}
